### ISSUE TITLE
Sounds very useful, tried to evaluate, getting Internal server error ...

### ISSUE THREAD

**Issue by ankumar** [keenlabs/capillary#11]
Play server process ID is 98978
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/akuma21/opensource/capillary-1.2/lib/ch.qos.logback.logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/akuma21/opensource/capillary-1.2/lib/org.slf4j.slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[error] application - 

! @6l9ldh4bc - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[JsonParseException: Illegal character ((CTRL-CHAR, code 7)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: java.io.StringReader@555c4144; line: 1, column: 2]]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 7)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: java.io.StringReader@555c4144; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:503) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:1695) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:562) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]

**Comment by gphat** [comment]
Hey @ankumar!

This probably means that your zk path (`-Dcapillary.kafka.zkroot`) is wrong? Whatever Capillary is getting back when it fetches data isn't valid JSON.  Perhaps double check the above setting with `zkCli.sh`?
