### ISSUE TITLE
Capillary not working 

### ISSUE THREAD

**Issue by dmakshay** [keenlabs/capillary#18]
I've been trying to use capillary for my storm and kafka cluster but it doesnt seem to work. I have this configuration.

capillary.zookeepers="192.168.125.20:2181"
capillary.kafka.zkroot="192.168.125.20:/home/storm/kafka_2.11-0.8.2.0"
capillary.storm.zkroot="192.168.125.20:/home/storm/apache-storm-0.9.3"

When I try to run capillary, it gives me an exception which is already posted here. 

https://github.com/keenlabs/capillary/issues/5

Here is the exception I get.

! @6mbg4bp7l - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[JsonParseException: Unexpected character ('.' (code 46)): Expected space separating root-level values
 at [Source: java.io.StringReader@24adb083; line: 1, column: 9]]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): Expected space separating root-level values
 at [Source: java.io.StringReader@24adb083; line: 1, column: 9]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:495) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyRootSpace(ReaderBasedJsonParser.java:1178) ~[com.fasterxml.jackson.core.jackson-core-2.3.2.jar:2.3.2]

Could anyone help me out here? Thanks in advance.

**Comment by jly59** [comment]
I just installed Capillary and I am having the issues noted in Issue #5:

[error] application - Zookeeper Path /consumers/console-consumer-13170/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-13170/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-13170/ids returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-43712/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-43712/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-43712/ids returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-15750/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-15750/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-15750/ids returned (null)!

I can see some items in those paths by using zkCli:
[zk: localhost:2181(CONNECTED) 4] ls /consumers/console-consumer-13170/ids
[]
[zk: localhost:2181(CONNECTED) 5] ls /consumers/console-consumer-13170/offsets
[ingest]
[zk: localhost:2181(CONNECTED) 6] ls /consumers/console-consumer-13170/owners 
[ingest]

So, offsets and owners are not null, but ids are. This is a distributed system with separate servers for Zookeeper, Kafka and Storm. I am starting Capillary with only the zookeeper specified:

bin/capillary -Dcapillary.zookeepers=zoo1:2181

since I'm not sure about the other startup parameters - the instructions say "If your Kafka chroots to a subdirectory (or whatever it's called)" and I'm not sure if that is true or not. How can I check to see what the Kafka and Storm config options should be?

**Comment by zhaoxiaojie0415** [comment]
I also got error when running it. Does the kafka.zkroot means the kafka nodes path in zookeeper? Still not understand the values of parameters clearly. My zknode path is like: /consumers/sys_group_hadoop/offsets/ALL_TOPIC/0
/kafkastorm/storm_test/partition_0

**Comment by zhaoxiaojie0415** [comment]
@dmakshay 
I think .kafka.zkroot is the path of kafka node in the zookeepers,  not the installtion path of kafka. Didn't it?

**Comment by dmakshay** [comment]
@zhaoxiaojie0415 yes that is right.

On Fri, Aug 14, 2015 at 1:10 PM, zhaoxiaojie0415 <notifications@github.com>
wrote:

> @dmakshay <https://github.com/dmakshay>
> I think .kafka.zkroot is the path of kafka node in the zookeepers, not the
> installtion path of kafka. Didn't it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keenlabs/capillary/issues/18#issuecomment-131006923>.
>



-- 
Thanks,
Akshay Madhuranath
