### ISSUE TITLE
Does not work with busy topology

### ISSUE THREAD

**Issue by binhnv** [keenlabs/capillary#21]
Hi,

This application works fine with not busy topology but it does not work when topology is busy and Storm write to ZK faster than this application can read.
I tested with my Trident topology and keep getting ```org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode``` exception. This is because this application try to read from znodes that are deleted by Storm.

-Binh

**Comment by espiegel** [comment]
I also get this error sometimes:

! @70hfklonm - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[NoNodeException: KeeperErrorCode = NoNode for /transactional/mytopicKafkaSpout/user/partition_59/53984332]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /transactional/mytopicKafkaSpout/user/partition_59/53984332
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:302) ~[org.apache.curator.curator-framework-2.6.0.jar:na]
	at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:291) ~[org.apache.curator.curator-framework-2.6.0.jar:na]
