### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by rja1** [keenlabs/capillary#5]
I'm likely not setting capillary.kafka.zkroot or capillary.storm.zkroot correctly, resulting in the below exception.

I've tried setting these parameters a number of times, using different paths - nothing seems to make a difference.

We're running two topologies.  One is using trident, the other is not.  We're running zookeeper-3.4.5, apache-storm-0.9.2-incubating and kafka_2.8.0-0.8.1.

We're not setting a storm or kafka root, so I would think whatever the app defaults to should be correct.  Here's the zookeeper structure.

[zk: localhost:2181(CONNECTED) 0] ls /
[transactional, realtimeroot, zookeeper, admin, consumers, config, controller, storm, brokers, controller_epoch]

Note that realtimeroot is the spout-root for one of the topos.  The trident topo seems to store it's data in /transactional/topo_name/user

Here's the error:
[root@mon01 bin]# ./capillary -Dcapillary.zookeepers=storm11:2181 
Play server process ID is 477
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/capillary-1.1/lib/ch.qos.logback.logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/capillary-1.1/lib/org.slf4j.slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0.0.0.0:9000
[error] application - 

! @6jb9j204i - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: Invalid path string "//transactional" caused by empty node name specified @1]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.2.jar:2.3.2]
        at play.api.DefaultApplication.handleError(Application.scala:402) ~[com.typesafe.play.play_2.10-2.3.2.jar:2.3.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) ~[com.typesafe.play.play_2.10-2.3.2.jar:2.3.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) ~[com.typesafe.play.play_2.10-2.3.2.jar:2.3.2]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) ~[org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.IllegalArgumentException: Invalid path string "//transactional" caused by empty node name specified @1
        at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:99) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1572) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214) ~[org.apache.curator.curator-framework-2.6.0.jar:na]
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) ~[org.apache.curator.curator-framework-2.6.0.jar:na]
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[org.apache.curator.curator-client-2.6.0.jar:na]

Please advise.  Thanks

**Comment by hsitaa** [comment]
https://github.com/keenlabs/capillary/issues/5

I see this Issue close.
But as the above comment states . I am also having the same issue.

My Structure of kafka and storm:

Machine 1 : Zookeeper kafka 
Machine 2 : Broker 1 , broker 2 , broker 3
Machine 3 : Storm zookeeper 

from Machine 1 i am running capillary too.

And initially get no error:
but when i browse the page on http://servername:9000/

it throws series of exceptions & Errors  :


[error] application - Zookeeper Path /consumers/console-consumer-77266/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-77266/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-77266/ids returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-51896/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-51896/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-51896/ids returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-40428/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-40428/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-40428/ids returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-96631/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-96631/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-96631/ids returned (null)!
[error] application - Zookeeper Path /consumers/test-consumer-group/offsets returned (null)!
[error] application - Zookeeper Path /consumers/test-consumer-group/owners returned (null)!
[error] application - Zookeeper Path /consumers/test-consumer-group/ids returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-26088/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-26088/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-26088/ids returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-32282/offsets returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-32282/owners returned (null)!
[error] application - Zookeeper Path /consumers/console-consumer-32282/ids returned (null)!
[error] application -

! @6lo66dmo4 - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))
        at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[com.typesafe.play.play-json_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[com.typesafe.play.play-json_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.json.JsResult$class.fold(JsResult.scala:77) ~[com.typesafe.play.play-json_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.json.JsError.fold(JsResult.scala:13) ~[com.typesafe.play.play-json_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.json.JsValue$class.as(JsValue.scala:65) ~[com.typesafe.play.play-json_2.10-2.3.4.jar:2.3.4]

**Comment by gphat** [comment]
Hey @hsitaa,

Can you show us some of the results from your zkClient.sh regarding the paths above that are reporting null?  Also, are you using the version currently in master?

This is mostly likely a configuration issue. Unless you can provide some help there we can't easily help you.
